version: "3.8"

services:
  postgres:
    image: postgres
    container_name: fundamentos-backend-pg
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fudamentos-backend
    volumes:
      - ./data/pg:/data/postgres

  nestjs-application:
    image: lscoti/my-node-app:prod
    container_name: node-trabalho
    expose:
      - 3000
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:docker@postgres:5432/fundamentos-backend?schema=public
    restart: on-failure

  nginx:
    image: nginx
    container_name: nginx-proxy
    ports:
      - 8080:80
    depends_on:
      - nestjs-application
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
